
# web端口、tomcat、header的配置
server:
  port: 8088
  servlet:
    context-path: /shop
  tomcat:
    uri-encoding: utf-8
  max-http-header-size: 80KB

# 配置数据源信息
spring:
  datasource:                                           # 数据源的相关配置
    type: com.zaxxer.hikari.HikariDataSource            # 数据源类型：HikariCP
    driver-class-name: com.mysql.cj.jdbc.Driver         # mysql驱动
    url: jdbc:mysql://localhost:3306/foodie-shop?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true
    username: root
    password: root
    hikari:
      connection-timeout: 30000         # 等待连接池分配连接的最大时长（毫秒），超过这个时长还没可用的连接则发生SQLException， 默认:30秒
      minimum-idle: 5                   # 最小连接数
      maximum-pool-size: 20             # 最大连接数
      auto-commit: true                 # 自动提交
      idle-timeout: 600000              # 连接超时的最大时长（毫秒），超时则被释放（retired），默认:10分钟
      pool-name: DateSourceHikariCP     # 连接池名字
      max-lifetime: 1800000             # 连接的生命时长（毫秒），超时而且没被使用则被释放（retired），默认:30分钟 1800000ms
      connection-test-query: SELECT 1   # 连接的时候测试sql

# mybatis & 通用mapper 配置
mybatis:
  type-aliases-package: com.summer.model        # 所有model类所在包路径
  mapper-locations: classpath:mapper/*.xml      # mapper映射文件
mapper:
  mappers: com.summer.my.mapper.MyMapper
  not-empty: false  # 比如  username != null , 框架是否会自动追加 username ！= ''
  identity: MYSQL   # 数据库方言


info:
  default_face: http://122.152.205.72:88/group1/M00/00/05/CpoxxFw_8_qAIlFXAAAcIhVPdSg994.png